# Generated by Django 4.2.6 on 2023-11-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
    ]
